### PR TITLE
Fix to accommodate query string parameters in the redirect URI if the request has query string params 

### PR DESCRIPTION
**Pull request by kala725**

### CODE REVIEW

**Comment by mattoperry** [comment]
Thanks for this.  I think there may not be a need for this filter.  Query strings are handled by the plugin already when it does its matching.  So for example if you want to match these two old ULRs and send them to different new URLs:

`yourdomain/some/path?p=1` => `yourdomain/some/new/post/1`
`yourdomain/some/path?p=2` => `yourdomain/some/new/post/2`

you would just import two separate redirect rules, one for each original URL, including query strings.

When your site is about to 404s in response to `yourdomain/some/path?p=1`, it will instead 301 to `yourdomain/some/new/post/1`, when it is about to 404 in response to `yourdomain/some/path?p=2`, it will 301 to `yourdomain/some/new/post/2`.

Does this make sense?

**Comment by kala725** [comment]
Hi @mattoperry :

First of all thanks for the consideration. After reading your comment, I strongly feel that we are not on the same plain about the requirement here.

Let's say I have created a redirect from:
/old-category/old-sub-category/post-name    ->   /post-name

After that,  If the request URL is same as old URL, there is no issue at all.

But, if the request URL is somewhat like : 
/old-category/old-sub-category/post-name?utm-source=google&utm_medium=email

Then it throws 404 error. The new filter will accommodate these query string parameters, which needs to be retained in the new URL also, using a small theme level code as defined below.

`
add_filter( 'wpcom_legacy_redirector_request_path', function( $uri ) { 
if ( strpos( $uri, '?' ) !== false ) { 
list( $uri, $query ) = explode( '?', $uri, 2 ); 
} 
return $uri; 
});

add_filter( 'wpcom_legacy_redirector_redirect_uri', function( $redirect_uri, $request_uri ) { 
if ( strpos( $response_uri, '?' ) !== false ) { 
list( $response_uri, $response_query ) = explode( '?', $response_uri, 2 ); 
} 
if ( strpos( $request_uri, '?' ) !== false ) { 
list( $request_uri, $request_query ) = explode( '?', $request_uri, 2 ); 
}

if ( ! ( empty( $request_query ) && empty($response_query ) ) ) { 
$response_query = $response_query . '&' . $request_query; 
$response_query = array_unique( explode( '&', $response_query ) ); 
$response_query = array_filter( $response_query ); 
$response_query = implode( '&', $response_query ); 
$redirect_uri .= '?' . $response_query; 
} 
return $redirect_uri; 
}, 10, 2 ); 
`

Please let me know, if any confusion/concern in the above code and the filter which I sent in this PR.

**Comment by philipjohn** [comment]
That should be easily handled with the existing `wpcom_legacy_redirector_request_path` filter.

If you want any version of `/old-category/old-sub-category/post-name` to redirect to `/post-name` a hook like this should achieve that;

```
// ** Untested code ** 
add_filter( 'wpcom_legacy_redirector_request_path', 'my_wpcom_legacy_redirector_request_path' );
function my_wpcom_legacy_redirector_request_path( $url ) {

    $components = wp_parse_url( $url );

    // Remove any query strings if we're visiting a particular URL
    if ( 
        false !== strpos( $components['path'], '/old-category/old-sub-category/post-name' ) &&
        isset( $components['query'] )
    ) {
        $url = str_replace( $components['query'], '', $url );
    }

    return $url;

}
```

The above code would have the effect of turning a redirect like this:

`/old-category/old-sub-category/post-name` => `/post-name`

into this:

`/old-category/old-sub-category/post-name*` => `/post-name`

by removing the query strings *before* the plugin uses the URL to check whether there are any matching redirect rules.

**Comment by kala725** [comment]
Hey @philipjohn,

I guess, you haven't looked at my code given in the comment above. I have already accommodated the request URI change (stripping out the query string in this given case). The objective here is bit different. I want to pass the request query params to the response. and for that purpose, this pr has been created.

Request you to go through my earlier comment.

**Comment by philipjohn** [comment]
The example was as follows:

> But, if the request URL is somewhat like :
> /old-category/old-sub-category/post-name?utm-source=google&utm_medium=email
> 
> Then it throws 404 error.

The filter I've suggested would convert that request URL to the following:

`/old-category/old-sub-category/post-name`

That's the request URL that the plugin would then use. It would find a match and redirect, based on your rule:

> Let's say I have created a redirect from:
> /old-category/old-sub-category/post-name -> /post-name

Have you tried implementing the filter I suggested?

**Comment by kala725** [comment]
Hi @philipjohn 

As I stated earlier, I have implemented the filter you suggested.

As you told, your suggested filter will convert the url from
`/old-category/old-sub-category/post-name?utm-source=google&utm_medium=email`
to
`/old-category/old-sub-category/post-name`

and then the redirect will happen like "
`/old-category/old-sub-category/post-name -> /post-name`

Which finally means that, redirect is

`/old-category/old-sub-category/post-name?utm-source=google&utm_medium=email -> /post-name
`

Upto here everything is fine.
But what if I need the below redirect to be in place
`/old-category/old-sub-category/post-name?utm-source=google&utm_medium=email -> /post-name?utm-source=google&utm_medium=email `

Please let me know, if you have doubt in the above statement. My objective is to retain the query string in the redirected URL also, which your filter cannot do.

Thats why I have added a new filter.

**Comment by kala725** [comment]
@philipjohn :

I am adding the code snippet , I have implemented for your reference

`add_filter( 'wpcom_legacy_redirector_request_path', function( $uri ) { 
	if ( strpos( $uri, '?' ) !== false ) { 
		list( $uri, $query ) = explode( '?', $uri, 2 ); 
	} 
	return $uri; 
});

add_filter( 'wpcom_legacy_redirector_redirect_uri', function( $redirect_uri, $request_uri ) { 
	if ( strpos( $response_uri, '?' ) !== false ) { 
		list( $response_uri, $response_query ) = explode( '?', $response_uri, 2 ); 
	} 
	if ( strpos( $request_uri, '?' ) !== false ) { 
		list( $request_uri, $request_query ) = explode( '?', $request_uri, 2 ); 
	}

	if ( ! ( empty( $request_query ) && empty($response_query ) ) ) { 
		$response_query = $response_query . '&' . $request_query; 
		$response_query = array_unique( explode( '&', $response_query ) ); 
		$response_query = array_filter( $response_query ); 
		$response_query = implode( '&', $response_query ); 
		$redirect_uri .= '?' . $response_query; 
	} 
	return $redirect_uri; 
}, 10, 2 ); `

**Comment by mdrovdahl** [comment]
pinging @philipjohn and/or @mattoperry for comment

**Comment by philipjohn** [comment]
Thanks for the extra detail @kala725 - that's helpful because I can see the legitimate use case for altering the redirect URL now.

So, I think there's a solution here, just not quite what's proposed as this new filter is too broad and has the potential for abuse.

What I'm thinking instead is that we have a filter that allows us to tell the plugin that some query parameters need to be preserved. E.g.;

```
add_filter( 'wpcom_legacy_redirector_preserve_query_params', function( $preserved_params ){
	array_push( $preserved_params,
		'utm_source',
		'utm_medium',
		'utm_campaign'
	);
	return $preserved_params;
} );
```

The plugin would then strip those parameters off the URL before [generating the hash](https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/9a01308d638cf25c73179fe3c626ddfdaba99f4e/wpcom-legacy-redirector.php#L121) it uses to retrieve the redirect URL, and add the parameters back on [just before doing the redirect](https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/9a01308d638cf25c73179fe3c626ddfdaba99f4e/wpcom-legacy-redirector.php#L63).

That would be a much more targeted way of achieving the end result, and a lot less open to abuse.

**Comment by GaryJones** [comment]
Looks like this was eventually resolved with #21.

Thanks for the perseverance and inspiration @kala725!

**Pull request closed without merging**
