### PR TITLE
Add dry run option for CSV import

### PR DESCRIPTION
**Pull request by jeremeylduvall**
Recently, I had to run the `import-from-csv` command, and I noticed there wasn't a `--dry_run` option available. To debug/test the CSV file prior to uploading, I ended up using a test site, which isn't the end of the world, but it's inconvenient. This quick PR adds a dry run option to confirm the CSV file and redirects are formatted correctly.

#### To test
- Create a mock CSV file. I created one using a single redirect from `/testing-a-redirect/ -> http://dev.test`.
- On your test site, run `wp wpcom-legacy-redirector import-from-csv --csv=[FILE PATH] --dry_run`. You should receive an output like this with the from, to, and row number:

```
---Dry Run---
Processing...
(CSV) Redirect would be added for /testing-a-redirect/ to http://dev.test at 1
```
- Import the redirect by removing the dry run flag. Assuming `/testing-a-redirect/` (or your test slug) 404's, the redirect should still work. You can further confirm the redirect was entered by using `wp post list --post_type=vip-legacy-redirect`

### CODE REVIEW

**Comment by sboisvert** [comment]
As written the dry run output kinda duplicates the input of the file. As in, what new information are we getting from the dry-run (as it stands)

One thing that I just thought of is that we currently have the error checking inside of insert_legacy_redirect(), this means that we can't check for any potential errors unless we try to insert a redirect. 

If we were to abstract that logic we could then have it be part of the dry run. We'd then be able to tell folks that hey this one won't work because it's not a valid URL or this one is not a public URL or this one sends to a 404, etc etc. I feel like that would be potentially very useful in terms of a dry run.

What are your thoughts?

**Comment by jeremeylduvall** [comment]
> As written the dry run output kinda duplicates the input of the file. As in, what new information are we getting from the dry-run (as it stands)

That's a good point. In this particular case, the CSV was corrupted so URLs were running together like this: `/redirect-from/http://example`. That wasn't obvious until you ran the import. This kind of dry run would surface that issue without causing a small mess.

I agree though that additional info would be helpful. I'll work on getting that added in!

**Comment by sboisvert** [comment]
> That's a good point. In this particular case, the CSV was corrupted so URLs were running together like this:

Ahhh, that makes sense!

**Comment by GaryJones** [comment]
We've got some validation happening, but it's not particularly decoupled from the insertion process. I think instead of a `--dry-run`, what we probably need is a `validate-csv` command, which can run all the checks over each potential insertion, and report back.

I'm putting this ticket into a future milestone until that validation code is extracted.

**Comment by GaryJones** [comment]
I've opened #58 and #59, so I'm going to close this PR.

**Pull request closed without merging**
