### PR TITLE
return home_url if post_parent does not exist

### PR DESCRIPTION
**Pull request by rodruiz**
- Return home_url if post_parent does not exist.
- Helps to check if "redirect from" URI already exists.
See: https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/master/wpcom-legacy-redirector.php#L89-L91

### CODE REVIEW

**Comment by rodruiz** [comment]
@mattoperry Could you review this PR?

**Comment by rodruiz** [comment]
@mattoperry Could you review this PR? :)
Thank you.

**Comment by mattoperry** [comment]
Hi @rodruiz ... I'm a bit foggy on why we'd want to do this -- could you explain?

**Comment by rodruiz** [comment]
Hi @mattoperry . You can reproduce the issue if you add a redirect:
 - from: "**/my-slug**"
- to: "**100**" (post id) but this post does not exist.
Then, when you try to add another redirect using the same "from URL":
- from: "**/my-slug**"
- to: "200"
the function [get_redirect_uri( $from_url )](https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/master/wpcom-legacy-redirector.php#L89-L91) returns false because "100" does not exist. In this case, you can insert multiples redirects using the same "from URL" because [the duplicate uri](https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/master/wpcom-legacy-redirector.php#L90) never is detected.

This PR is to return "home_url()" when post_id does not exist. Then "**get_redirect_uri( $from_url )**" returns true and a "duplicate uri" is detected.

Thanks.

**Comment by rodruiz** [comment]
ping @mattoperry

**Comment by mattoperry** [comment]
Thanks @rodruiz I understand now.  I guess the only question I have is why we'd return `home_url` rather than an error or something if the post doesn't exist?  Doing so might (I think -- I'd have to check?) let us prevent redirects like this from being inserted in the first place ... of course it could always turn out that the post gets deleted and this happens anyway ... 

In any case returning home_url seems kind of wrong, because it could result in unintended behavior (redirecting stuff to the homepage without intending to)

**Comment by rodruiz** [comment]
@mattoperry I think we have to change get_redirect_uri method. Now just returns (false or string). Should returns (**false, string or WP_Error**). Why is not returning a [WP_Error here](https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/master/wpcom-legacy-redirector.php#L117-L119)? 
In this method, we have to return a WP_Error instead of **home_url** when post does not exist :)
What do you think?

**Comment by rodruiz** [comment]
@mattoperry Last commit should fix the issue.
Thanks.

**Comment by rodruiz** [comment]
@mattoperry Closing this PR and moving the code to PR #18.

**Pull request closed without merging**
